apiVersion: v1
kind: Pod
metadata:
  name: pod-with-wasm-workload
  annotations:
    module.wasm.image/variant: compat
spec:
  containers:
  - name: wasm-container
    image: quay.io/ifont/wasmtime-hello
